import 'package:vaxpsam/domain/wireless_tool.dart';

class WirelessSecurityData {
  static const List<String> kAllToolPackages = [
    'aircrack-ng',
    'reaver',
    'pixiewps',
    'kismet',
    'hcxdumptool',
    'mdk3',
    'macchanger',
    'bluetop',
    'hcxtools',
    'bluez',
    'wireless-tools', // Iwevent, Iwconfig, Iwlist
  ];

  static const List<WirelessTool> kWirelessTools = [
    WirelessTool(
      name: 'Aircrack-ng',
      package: 'aircrack-ng',
      description: 'Toolkit for assessing 802.11 (Wi-Fi) security',
    ),
    WirelessTool(
      name: 'Reaver',
      package: 'reaver',
      description: 'PIN guessing tool for the WPS protocol',
    ),
    WirelessTool(
      name: 'Pixiewps',
      package: 'pixiewps',
      description: 'Offline PIN bruteforce attack tool for WPS',
    ),
    WirelessTool(
      name: 'Kismet',
      package: 'kismet',
      description:
          'Intrusion detection system (IDS) and scanner for 802.11 and Bluetooth networks',
    ),
    WirelessTool(
      name: 'Hcxdumptool',
      package: 'hcxdumptool',
      description: 'Handshake packet capture tool for WPA/WPA2',
    ),
    WirelessTool(
      name: 'MDK3',
      package: 'mdk3',
      description: 'Advanced Wi-Fi penetration testing tool (DoS attacks)',
    ),
    WirelessTool(
      name: 'Macchanger',
      package: 'macchanger',
      description: 'Tool for changing the MAC address of network interfaces',
    ),
    WirelessTool(
      name: 'Bluetop',
      package: 'bluetop',
      description: 'Graphical Bluetooth monitor (helps with device discovery)',
    ),
    WirelessTool(
      name: 'Hcxtools',
      package: 'hcxtools',
      description: 'Utility for converting hash formats to WPA/WPA2',
    ),
    WirelessTool(
      name: 'Bluez',
      package: 'bluez',
      description:
          'Official Bluetooth package for Linux (required for running Bluetooth tools)',
    ),
    WirelessTool(
      name: 'Iwevent',
      package: 'wireless-tools',
      description: 'Displays events generated by the wireless interface',
    ),
    WirelessTool(
      name: 'Iwconfig',
      package: 'wireless-tools',
      description: 'Configures wireless interfaces',
    ),
    WirelessTool(
      name: 'Iwlist',
      package: 'wireless-tools',
      description: 'Scans the list of access points',
    ),
  ];
}
